export default {
    IC_HOME:require('../Assest/Images/Home.png'),
    IC_SCANNER:require('../Assest/Images/Scanner.png'),
    IC_SETTING:require('../Assest/Images/Setting.png'),
    IC_SNOW_FREZZE:require('../Assest/Images/snowflake.png'),
    IMG_FREZZ:require('../Assest/Images/FrezzImg.png'),
    IMG_BACKGROUND_CARD:require('../Assest/Images/backgroundImg.png'),
    IMG_BANK_NAME:require('../Assest/Images/bankName.png'),
    IMG_COPY:require('../Assest/Images/copyImg.png'),
    IMG_HIDE_EYE:require('../Assest/Images/hideEyeImg.png'),
    IMG_LOGO:require('../Assest/Images/logo.png'),
    IMG_PAYMET_METHOD:require('../Assest/Images/paymetMethodImg.png'),
    IMG_SECURE:require('../Assest/Images/secureImg.png'),
    IMG_DESIGN_FOR_NUMBER:require('../Assest/Images/Union.png'),
}